
def översätt():
    #En input som tar in meningen som skas översättas
    s = input("skriv in en text som skall översättas till Rövarspråk: ")

    #byt ut alla vokaler
    s = s.replace('b', 'bob')
    s = s.replace('c', 'coc')
    s = s.replace('d', 'dod')
    s = s.replace('f', 'fof')
    s = s.replace('g', 'gog')
    s = s.replace('h', 'hoh')
    s = s.replace('j', 'joj')
    s = s.replace('k', 'kok')
    s = s.replace('l', 'lol')
    s = s.replace('m', 'mom')
    s = s.replace('n', 'non')
    s = s.replace('p', 'pop')
    s = s.replace('q', 'qoq')
    s = s.replace('r', 'ror')
    s = s.replace('s', 'sos')
    s = s.replace('t', 'tot')
    s = s.replace('v', 'vov')
    s = s.replace('z', 'zoz')
    s = s.replace('x', 'xox')
    
    #gör till små bokstäver
    s = s.replace('A', 'a')
    s = s.replace('B', 'bob')
    s = s.replace('C', 'coc')
    s = s.replace('D', 'dod')
    s = s.replace('E', 'e')
    s = s.replace('F', 'fof')
    s = s.replace('G', 'gog')
    s = s.replace('H', 'hoh')
    s = s.replace('I', 'i')
    s = s.replace('J', 'joj')
    s = s.replace('K', 'kok')
    s = s.replace('L', 'lol')
    s = s.replace('M', 'mom')
    s = s.replace('N', 'non')
    s = s.replace('O', 'o')
    s = s.replace('P', 'pop')
    s = s.replace('Q', 'qoq')
    s = s.replace('R', 'ror')
    s = s.replace('S', 'sos')
    s = s.replace('T', 'tot')
    s = s.replace('U', 'u')
    s = s.replace('V', 'vov')
    s = s.replace('W', 'w')
    s = s.replace('Z', 'zoz')
    s = s.replace('Y', 'y')
    s = s.replace('X', 'xox')
    s = s.replace('Å', 'å')
    s = s.replace('Ä', 'ä')
    s = s.replace('Ö', 'ö')

    print(s)

översätt()
#En input som tar in meningen som skas översättas
